baseURL = 'http://albo3.com/'
languageCode = 'en-us'
title = 'albo3.com'
theme = 'myTheme'
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 3
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3